### ISSUE TITLE
Can't get an TOTP

### ISSUE THREAD

**Issue by thorko** [monich/harbour-yubikey#2]
Hi, 
when I touch the yubikey I'll get a list of all TOTP tokens stored at the key. But I can't get a TOTP token for one of the accounts listed.
I press the yubikey several times but nothing shows up. How can I select the account and get a TOTP token displayed.

Update: It is not working when the TOTP token is setup to require yubikey touch. It works if no touch is required.

**Comment by monich** [comment]
Ah, it wasn't clear to me what that touch thing means. Somehow I thought that it was an HOTP specific feature but apparently it's not. I'll take another look.

**Comment by monich** [comment]
Try release 1.0.1

**Comment by thorko** [comment]
It works perfectly, thanks a lot
